// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/google/uuid"
)

type Media interface {
	IsMedia()
	GetID() uuid.UUID
	GetTitle() string
	GetReleaseDate() *string
	GetDescription() *string
	GetCoverURL() *string
	GetCreators() []*Creator
	GetPlatforms() []*Platform
	GetTags() []*Tag
	GetRatings() []*Rating
	GetAverageRating() *float64
	GetSearchDepth() int32
	GetMyActivity() *UserActivity
}

type ActivityStatus struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Book struct {
	ID            uuid.UUID     `json:"id"`
	Title         string        `json:"title"`
	ReleaseDate   *string       `json:"releaseDate,omitempty"`
	Description   *string       `json:"description,omitempty"`
	CoverURL      *string       `json:"coverUrl,omitempty"`
	Creators      []*Creator    `json:"creators"`
	Authors       []*Creator    `json:"authors"`
	Platforms     []*Platform   `json:"platforms"`
	Tags          []*Tag        `json:"tags"`
	Subjects      []*Tag        `json:"subjects"`
	Publishers    []string      `json:"publishers"`
	Ratings       []*Rating     `json:"ratings"`
	AverageRating *float64      `json:"averageRating,omitempty"`
	SearchDepth   int32         `json:"searchDepth"`
	MyActivity    *UserActivity `json:"myActivity,omitempty"`
	Pages         *int32        `json:"pages,omitempty"`
	Isbn          *string       `json:"isbn,omitempty"`
	Publisher     *string       `json:"publisher,omitempty"`
}

func (Book) IsMedia()                     {}
func (this Book) GetID() uuid.UUID        { return this.ID }
func (this Book) GetTitle() string        { return this.Title }
func (this Book) GetReleaseDate() *string { return this.ReleaseDate }
func (this Book) GetDescription() *string { return this.Description }
func (this Book) GetCoverURL() *string    { return this.CoverURL }
func (this Book) GetCreators() []*Creator {
	if this.Creators == nil {
		return nil
	}
	interfaceSlice := make([]*Creator, 0, len(this.Creators))
	for _, concrete := range this.Creators {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Book) GetPlatforms() []*Platform {
	if this.Platforms == nil {
		return nil
	}
	interfaceSlice := make([]*Platform, 0, len(this.Platforms))
	for _, concrete := range this.Platforms {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Book) GetTags() []*Tag {
	if this.Tags == nil {
		return nil
	}
	interfaceSlice := make([]*Tag, 0, len(this.Tags))
	for _, concrete := range this.Tags {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Book) GetRatings() []*Rating {
	if this.Ratings == nil {
		return nil
	}
	interfaceSlice := make([]*Rating, 0, len(this.Ratings))
	for _, concrete := range this.Ratings {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Book) GetAverageRating() *float64   { return this.AverageRating }
func (this Book) GetSearchDepth() int32        { return this.SearchDepth }
func (this Book) GetMyActivity() *UserActivity { return this.MyActivity }

type CastAndCrewResult struct {
	Cast        []*Person       `json:"cast"`
	Crew        []*Person       `json:"crew"`
	CastCredits []*PersonCredit `json:"castCredits"`
	CrewCredits []*CrewCredit   `json:"crewCredits"`
}

type CreateActivityInput struct {
	MediaID    uuid.UUID `json:"mediaId"`
	StatusID   int32     `json:"statusId"`
	Rating     *float64  `json:"rating,omitempty"`
	Review     *string   `json:"review,omitempty"`
	StartedAt  *string   `json:"startedAt,omitempty"`
	FinishedAt *string   `json:"finishedAt,omitempty"`
}

type CreateBookInput struct {
	Title       string   `json:"title"`
	ReleaseDate *string  `json:"releaseDate,omitempty"`
	Description *string  `json:"description,omitempty"`
	CoverURL    *string  `json:"coverUrl,omitempty"`
	Pages       *int32   `json:"pages,omitempty"`
	Isbn        *string  `json:"isbn,omitempty"`
	Publisher   *string  `json:"publisher,omitempty"`
	Authors     []string `json:"authors,omitempty"`
	Publishers  []string `json:"publishers,omitempty"`
	Subjects    []string `json:"subjects,omitempty"`
	SearchDepth *int32   `json:"searchDepth,omitempty"`
}

type CreateGameInput struct {
	Title        string   `json:"title"`
	ReleaseDate  *string  `json:"releaseDate,omitempty"`
	Description  *string  `json:"description,omitempty"`
	CoverURL     *string  `json:"coverUrl,omitempty"`
	ExternalID   *string  `json:"externalId,omitempty"`
	Genre        []string `json:"genre"`
	Themes       []string `json:"themes,omitempty"`
	Keywords     []string `json:"keywords,omitempty"`
	GameModes    []string `json:"gameModes,omitempty"`
	Perspectives []string `json:"perspectives,omitempty"`
	Franchises   []string `json:"franchises,omitempty"`
	Platforms    []string `json:"platforms,omitempty"`
	EsrbRating   *string  `json:"esrbRating,omitempty"`
	Multiplayer  *bool    `json:"multiplayer,omitempty"`
	SearchDepth  *int32   `json:"searchDepth,omitempty"`
}

type CreateMovieInput struct {
	Title               string   `json:"title"`
	ReleaseDate         *string  `json:"releaseDate,omitempty"`
	Description         *string  `json:"description,omitempty"`
	CoverURL            *string  `json:"coverUrl,omitempty"`
	ExternalID          *string  `json:"externalId,omitempty"`
	Runtime             *int32   `json:"runtime,omitempty"`
	Budget              *int32   `json:"budget,omitempty"`
	BoxOffice           *int32   `json:"boxOffice,omitempty"`
	Cast                []string `json:"cast,omitempty"`
	Crew                []string `json:"crew,omitempty"`
	ProductionCompanies []string `json:"productionCompanies,omitempty"`
	Genres              []string `json:"genres,omitempty"`
	SearchDepth         *int32   `json:"searchDepth,omitempty"`
	MaxConnections      *int32   `json:"maxConnections,omitempty"`
}

type CreateMusicAlbumInput struct {
	Title       string  `json:"title"`
	ReleaseDate *string `json:"releaseDate,omitempty"`
	Description *string `json:"description,omitempty"`
	CoverURL    *string `json:"coverUrl,omitempty"`
	TrackCount  *int32  `json:"trackCount,omitempty"`
	Duration    *int32  `json:"duration,omitempty"`
	Label       *string `json:"label,omitempty"`
	SearchDepth *int32  `json:"searchDepth,omitempty"`
}

type CreateTVShowInput struct {
	Title               string   `json:"title"`
	ReleaseDate         *string  `json:"releaseDate,omitempty"`
	Description         *string  `json:"description,omitempty"`
	CoverURL            *string  `json:"coverUrl,omitempty"`
	ExternalID          *string  `json:"externalId,omitempty"`
	Seasons             *int32   `json:"seasons,omitempty"`
	Episodes            *int32   `json:"episodes,omitempty"`
	Status              *string  `json:"status,omitempty"`
	Cast                []string `json:"cast,omitempty"`
	Crew                []string `json:"crew,omitempty"`
	ProductionCompanies []string `json:"productionCompanies,omitempty"`
	Genres              []string `json:"genres,omitempty"`
	SearchDepth         *int32   `json:"searchDepth,omitempty"`
	MaxConnections      *int32   `json:"maxConnections,omitempty"`
}

type CreateUserInput struct {
	Name         string  `json:"name"`
	Email        string  `json:"email"`
	AuthProvider *string `json:"authProvider,omitempty"`
	AuthSubject  *string `json:"authSubject,omitempty"`
	AvatarURL    *string `json:"avatarUrl,omitempty"`
}

type Creator struct {
	ID         uuid.UUID    `json:"id"`
	Name       string       `json:"name"`
	Role       *CreatorRole `json:"role"`
	MediaItems []Media      `json:"mediaItems"`
}

type CreatorRole struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type CrewCredit struct {
	Person     *Person `json:"person"`
	Name       string  `json:"name"`
	Job        *string `json:"job,omitempty"`
	Department *string `json:"department,omitempty"`
}

type Game struct {
	ID            uuid.UUID     `json:"id"`
	Title         string        `json:"title"`
	ReleaseDate   *string       `json:"releaseDate,omitempty"`
	Description   *string       `json:"description,omitempty"`
	CoverURL      *string       `json:"coverUrl,omitempty"`
	Creators      []*Creator    `json:"creators"`
	Platforms     []*Platform   `json:"platforms"`
	Tags          []*Tag        `json:"tags"`
	Ratings       []*Rating     `json:"ratings"`
	AverageRating *float64      `json:"averageRating,omitempty"`
	SearchDepth   int32         `json:"searchDepth"`
	MyActivity    *UserActivity `json:"myActivity,omitempty"`
	Genre         []string      `json:"genre"`
	Themes        []string      `json:"themes"`
	Keywords      []string      `json:"keywords"`
	GameModes     []string      `json:"gameModes"`
	Perspectives  []string      `json:"perspectives"`
	Franchises    []string      `json:"franchises"`
	PlatformsList []string      `json:"platformsList"`
	EsrbRating    *string       `json:"esrbRating,omitempty"`
	Multiplayer   *bool         `json:"multiplayer,omitempty"`
}

func (Game) IsMedia()                     {}
func (this Game) GetID() uuid.UUID        { return this.ID }
func (this Game) GetTitle() string        { return this.Title }
func (this Game) GetReleaseDate() *string { return this.ReleaseDate }
func (this Game) GetDescription() *string { return this.Description }
func (this Game) GetCoverURL() *string    { return this.CoverURL }
func (this Game) GetCreators() []*Creator {
	if this.Creators == nil {
		return nil
	}
	interfaceSlice := make([]*Creator, 0, len(this.Creators))
	for _, concrete := range this.Creators {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Game) GetPlatforms() []*Platform {
	if this.Platforms == nil {
		return nil
	}
	interfaceSlice := make([]*Platform, 0, len(this.Platforms))
	for _, concrete := range this.Platforms {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Game) GetTags() []*Tag {
	if this.Tags == nil {
		return nil
	}
	interfaceSlice := make([]*Tag, 0, len(this.Tags))
	for _, concrete := range this.Tags {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Game) GetRatings() []*Rating {
	if this.Ratings == nil {
		return nil
	}
	interfaceSlice := make([]*Rating, 0, len(this.Ratings))
	for _, concrete := range this.Ratings {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Game) GetAverageRating() *float64   { return this.AverageRating }
func (this Game) GetSearchDepth() int32        { return this.SearchDepth }
func (this Game) GetMyActivity() *UserActivity { return this.MyActivity }

type Genre struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Movies []*Movie  `json:"movies"`
}

type MediaSuggestion struct {
	Title      string  `json:"title"`
	Year       *int32  `json:"year,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	ImageURL   *string `json:"imageUrl,omitempty"`
	Subtitle   *string `json:"subtitle,omitempty"`
}

type Movie struct {
	ID                  uuid.UUID            `json:"id"`
	Title               string               `json:"title"`
	ReleaseDate         *string              `json:"releaseDate,omitempty"`
	Description         *string              `json:"description,omitempty"`
	CoverURL            *string              `json:"coverUrl,omitempty"`
	Creators            []*Creator           `json:"creators"`
	Platforms           []*Platform          `json:"platforms"`
	Tags                []*Tag               `json:"tags"`
	Ratings             []*Rating            `json:"ratings"`
	AverageRating       *float64             `json:"averageRating,omitempty"`
	SearchDepth         int32                `json:"searchDepth"`
	MyActivity          *UserActivity        `json:"myActivity,omitempty"`
	Runtime             *int32               `json:"runtime,omitempty"`
	Budget              *int32               `json:"budget,omitempty"`
	BoxOffice           *int32               `json:"boxOffice,omitempty"`
	Cast                []*Person            `json:"cast"`
	Crew                []*Person            `json:"crew"`
	CastCredits         []*PersonCredit      `json:"castCredits"`
	CrewCredits         []*CrewCredit        `json:"crewCredits"`
	ProductionCompanies []*ProductionCompany `json:"productionCompanies"`
	Genres              []*Genre             `json:"genres"`
	ProductionCountries []*ProductionCountry `json:"productionCountries"`
}

func (Movie) IsMedia()                     {}
func (this Movie) GetID() uuid.UUID        { return this.ID }
func (this Movie) GetTitle() string        { return this.Title }
func (this Movie) GetReleaseDate() *string { return this.ReleaseDate }
func (this Movie) GetDescription() *string { return this.Description }
func (this Movie) GetCoverURL() *string    { return this.CoverURL }
func (this Movie) GetCreators() []*Creator {
	if this.Creators == nil {
		return nil
	}
	interfaceSlice := make([]*Creator, 0, len(this.Creators))
	for _, concrete := range this.Creators {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Movie) GetPlatforms() []*Platform {
	if this.Platforms == nil {
		return nil
	}
	interfaceSlice := make([]*Platform, 0, len(this.Platforms))
	for _, concrete := range this.Platforms {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Movie) GetTags() []*Tag {
	if this.Tags == nil {
		return nil
	}
	interfaceSlice := make([]*Tag, 0, len(this.Tags))
	for _, concrete := range this.Tags {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Movie) GetRatings() []*Rating {
	if this.Ratings == nil {
		return nil
	}
	interfaceSlice := make([]*Rating, 0, len(this.Ratings))
	for _, concrete := range this.Ratings {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Movie) GetAverageRating() *float64   { return this.AverageRating }
func (this Movie) GetSearchDepth() int32        { return this.SearchDepth }
func (this Movie) GetMyActivity() *UserActivity { return this.MyActivity }

type MusicAlbum struct {
	ID            uuid.UUID     `json:"id"`
	Title         string        `json:"title"`
	ReleaseDate   *string       `json:"releaseDate,omitempty"`
	Description   *string       `json:"description,omitempty"`
	CoverURL      *string       `json:"coverUrl,omitempty"`
	Creators      []*Creator    `json:"creators"`
	Platforms     []*Platform   `json:"platforms"`
	Tags          []*Tag        `json:"tags"`
	Ratings       []*Rating     `json:"ratings"`
	AverageRating *float64      `json:"averageRating,omitempty"`
	SearchDepth   int32         `json:"searchDepth"`
	MyActivity    *UserActivity `json:"myActivity,omitempty"`
	TrackCount    *int32        `json:"trackCount,omitempty"`
	Duration      *int32        `json:"duration,omitempty"`
	Label         *string       `json:"label,omitempty"`
}

func (MusicAlbum) IsMedia()                     {}
func (this MusicAlbum) GetID() uuid.UUID        { return this.ID }
func (this MusicAlbum) GetTitle() string        { return this.Title }
func (this MusicAlbum) GetReleaseDate() *string { return this.ReleaseDate }
func (this MusicAlbum) GetDescription() *string { return this.Description }
func (this MusicAlbum) GetCoverURL() *string    { return this.CoverURL }
func (this MusicAlbum) GetCreators() []*Creator {
	if this.Creators == nil {
		return nil
	}
	interfaceSlice := make([]*Creator, 0, len(this.Creators))
	for _, concrete := range this.Creators {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this MusicAlbum) GetPlatforms() []*Platform {
	if this.Platforms == nil {
		return nil
	}
	interfaceSlice := make([]*Platform, 0, len(this.Platforms))
	for _, concrete := range this.Platforms {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this MusicAlbum) GetTags() []*Tag {
	if this.Tags == nil {
		return nil
	}
	interfaceSlice := make([]*Tag, 0, len(this.Tags))
	for _, concrete := range this.Tags {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this MusicAlbum) GetRatings() []*Rating {
	if this.Ratings == nil {
		return nil
	}
	interfaceSlice := make([]*Rating, 0, len(this.Ratings))
	for _, concrete := range this.Ratings {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this MusicAlbum) GetAverageRating() *float64   { return this.AverageRating }
func (this MusicAlbum) GetSearchDepth() int32        { return this.SearchDepth }
func (this MusicAlbum) GetMyActivity() *UserActivity { return this.MyActivity }

type Mutation struct {
}

type Person struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	ExternalID *string   `json:"externalID,omitempty"`
	ActedIn    []*Movie  `json:"actedIn"`
	CrewOn     []*Movie  `json:"crewOn"`
}

type PersonCredit struct {
	Person    *Person `json:"person"`
	Name      string  `json:"name"`
	Character *string `json:"character,omitempty"`
	Order     *int32  `json:"order,omitempty"`
}

type Platform struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	BaseURL    *string   `json:"baseUrl,omitempty"`
	MediaItems []Media   `json:"mediaItems"`
}

type ProductionCompany struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Produced []*Movie  `json:"produced"`
}

type ProductionCountry struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Movies []*Movie  `json:"movies"`
}

type Query struct {
}

type Rating struct {
	User    *User   `json:"user"`
	Media   Media   `json:"media"`
	Score   float64 `json:"score"`
	RatedAt string  `json:"ratedAt"`
}

type Recommendation struct {
	ID          uuid.UUID `json:"id"`
	User        *User     `json:"user"`
	Media       Media     `json:"media"`
	Recommender *User     `json:"recommender,omitempty"`
	Source      *string   `json:"source,omitempty"`
	Score       *float64  `json:"score,omitempty"`
}

type SearchStatus struct {
	State       SearchState `json:"state"`
	CompletedAt *string     `json:"completedAt,omitempty"`
}

type TVShow struct {
	ID                  uuid.UUID            `json:"id"`
	Title               string               `json:"title"`
	ReleaseDate         *string              `json:"releaseDate,omitempty"`
	Description         *string              `json:"description,omitempty"`
	CoverURL            *string              `json:"coverUrl,omitempty"`
	Creators            []*Creator           `json:"creators"`
	Platforms           []*Platform          `json:"platforms"`
	Tags                []*Tag               `json:"tags"`
	Ratings             []*Rating            `json:"ratings"`
	AverageRating       *float64             `json:"averageRating,omitempty"`
	SearchDepth         int32                `json:"searchDepth"`
	MyActivity          *UserActivity        `json:"myActivity,omitempty"`
	Seasons             *int32               `json:"seasons,omitempty"`
	Episodes            *int32               `json:"episodes,omitempty"`
	Status              *string              `json:"status,omitempty"`
	Cast                []*Person            `json:"cast"`
	Crew                []*Person            `json:"crew"`
	CastCredits         []*PersonCredit      `json:"castCredits"`
	CrewCredits         []*CrewCredit        `json:"crewCredits"`
	ProductionCompanies []*ProductionCompany `json:"productionCompanies"`
	Genres              []*Genre             `json:"genres"`
	ProductionCountries []*ProductionCountry `json:"productionCountries"`
}

func (TVShow) IsMedia()                     {}
func (this TVShow) GetID() uuid.UUID        { return this.ID }
func (this TVShow) GetTitle() string        { return this.Title }
func (this TVShow) GetReleaseDate() *string { return this.ReleaseDate }
func (this TVShow) GetDescription() *string { return this.Description }
func (this TVShow) GetCoverURL() *string    { return this.CoverURL }
func (this TVShow) GetCreators() []*Creator {
	if this.Creators == nil {
		return nil
	}
	interfaceSlice := make([]*Creator, 0, len(this.Creators))
	for _, concrete := range this.Creators {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this TVShow) GetPlatforms() []*Platform {
	if this.Platforms == nil {
		return nil
	}
	interfaceSlice := make([]*Platform, 0, len(this.Platforms))
	for _, concrete := range this.Platforms {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this TVShow) GetTags() []*Tag {
	if this.Tags == nil {
		return nil
	}
	interfaceSlice := make([]*Tag, 0, len(this.Tags))
	for _, concrete := range this.Tags {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this TVShow) GetRatings() []*Rating {
	if this.Ratings == nil {
		return nil
	}
	interfaceSlice := make([]*Rating, 0, len(this.Ratings))
	for _, concrete := range this.Ratings {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this TVShow) GetAverageRating() *float64   { return this.AverageRating }
func (this TVShow) GetSearchDepth() int32        { return this.SearchDepth }
func (this TVShow) GetMyActivity() *UserActivity { return this.MyActivity }

type Tag struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Type string    `json:"type"`
}

type UpdateActivityInput struct {
	StatusID   *int32   `json:"statusId,omitempty"`
	Rating     *float64 `json:"rating,omitempty"`
	Review     *string  `json:"review,omitempty"`
	StartedAt  *string  `json:"startedAt,omitempty"`
	FinishedAt *string  `json:"finishedAt,omitempty"`
}

type UpdateUserInput struct {
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type User struct {
	ID              uuid.UUID         `json:"id"`
	Name            string            `json:"name"`
	Email           string            `json:"email"`
	AuthProvider    *string           `json:"authProvider,omitempty"`
	AuthSubject     *string           `json:"authSubject,omitempty"`
	AvatarURL       *string           `json:"avatarUrl,omitempty"`
	Activities      []*UserActivity   `json:"activities"`
	Ratings         []*Rating         `json:"ratings"`
	Favorites       []Media           `json:"favorites"`
	Recommendations []*Recommendation `json:"recommendations"`
}

type UserActivity struct {
	ID             uuid.UUID       `json:"id"`
	User           *User           `json:"user"`
	Media          Media           `json:"media"`
	Status         *ActivityStatus `json:"status"`
	Rating         *float64        `json:"rating,omitempty"`
	Review         *string         `json:"review,omitempty"`
	StartedAt      *string         `json:"startedAt,omitempty"`
	FinishedAt     *string         `json:"finishedAt,omitempty"`
	SourcePlatform *Platform       `json:"sourcePlatform,omitempty"`
}

type MediaType string

const (
	MediaTypeMovie MediaType = "MOVIE"
	MediaTypeTv    MediaType = "TV"
	MediaTypeBook  MediaType = "BOOK"
	MediaTypeGame  MediaType = "GAME"
	MediaTypeMusic MediaType = "MUSIC"
)

var AllMediaType = []MediaType{
	MediaTypeMovie,
	MediaTypeTv,
	MediaTypeBook,
	MediaTypeGame,
	MediaTypeMusic,
}

func (e MediaType) IsValid() bool {
	switch e {
	case MediaTypeMovie, MediaTypeTv, MediaTypeBook, MediaTypeGame, MediaTypeMusic:
		return true
	}
	return false
}

func (e MediaType) String() string {
	return string(e)
}

func (e *MediaType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaType", str)
	}
	return nil
}

func (e MediaType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchState string

const (
	SearchStateIdle      SearchState = "IDLE"
	SearchStateRunning   SearchState = "RUNNING"
	SearchStateCompleted SearchState = "COMPLETED"
)

var AllSearchState = []SearchState{
	SearchStateIdle,
	SearchStateRunning,
	SearchStateCompleted,
}

func (e SearchState) IsValid() bool {
	switch e {
	case SearchStateIdle, SearchStateRunning, SearchStateCompleted:
		return true
	}
	return false
}

func (e SearchState) String() string {
	return string(e)
}

func (e *SearchState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchState", str)
	}
	return nil
}

func (e SearchState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
