package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/grillinr/nq/graph/model"
	"github.com/grillinr/nq/metadata"
)

// MyActivity is the resolver for the myActivity field.
func (r *bookResolver) MyActivity(ctx context.Context, obj *model.Book) (*model.UserActivity, error) {
	return r.getMyActivityForMedia(ctx, obj.ID)
}

// RelatedMedia is the resolver for the relatedMedia field.
func (r *bookResolver) RelatedMedia(ctx context.Context, obj *model.Book, limit *int32) ([]model.Media, error) {
	return r.Repo.GetRelatedMedia(ctx, obj.ID, resolveLimit(limit))
}

// From is the resolver for the from field.
func (r *friendRequestResolver) From(ctx context.Context, obj *model.FriendRequest) (*model.User, error) {
	if obj.From != nil {
		return obj.From, nil
	}
	return nil, nil
}

// To is the resolver for the to field.
func (r *friendRequestResolver) To(ctx context.Context, obj *model.FriendRequest) (*model.User, error) {
	if obj.To != nil {
		return obj.To, nil
	}
	return nil, nil
}

// MyActivity is the resolver for the myActivity field.
func (r *gameResolver) MyActivity(ctx context.Context, obj *model.Game) (*model.UserActivity, error) {
	return r.getMyActivityForMedia(ctx, obj.ID)
}

// RelatedMedia is the resolver for the relatedMedia field.
func (r *gameResolver) RelatedMedia(ctx context.Context, obj *model.Game, limit *int32) ([]model.Media, error) {
	return r.Repo.GetRelatedMedia(ctx, obj.ID, resolveLimit(limit))
}

// MyActivity is the resolver for the myActivity field.
func (r *movieResolver) MyActivity(ctx context.Context, obj *model.Movie) (*model.UserActivity, error) {
	return r.getMyActivityForMedia(ctx, obj.ID)
}

// RelatedMedia is the resolver for the relatedMedia field.
func (r *movieResolver) RelatedMedia(ctx context.Context, obj *model.Movie, limit *int32) ([]model.Media, error) {
	return r.Repo.GetRelatedMedia(ctx, obj.ID, resolveLimit(limit))
}

// MyActivity is the resolver for the myActivity field.
func (r *musicAlbumResolver) MyActivity(ctx context.Context, obj *model.MusicAlbum) (*model.UserActivity, error) {
	return r.getMyActivityForMedia(ctx, obj.ID)
}

// RelatedMedia is the resolver for the relatedMedia field.
func (r *musicAlbumResolver) RelatedMedia(ctx context.Context, obj *model.MusicAlbum, limit *int32) ([]model.Media, error) {
	return r.Repo.GetRelatedMedia(ctx, obj.ID, resolveLimit(limit))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	return r.Repo.CreateUser(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, input model.UpdateUserInput) (*model.User, error) {
	return r.Repo.UpdateUser(ctx, id, input)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (bool, error) {
	if err := r.Repo.DeleteUser(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateMovie is the resolver for the createMovie field.
func (r *mutationResolver) CreateMovie(ctx context.Context, input model.CreateMovieInput) (*model.Movie, error) {
	movie, err := r.Repo.CreateMovie(ctx, input)
	if err != nil {
		return nil, err
	}

	// If searchDepth is 0 (directly searched), perform recursive search on connections
	searchDepth := int32(0)
	if input.SearchDepth != nil {
		searchDepth = *input.SearchDepth
	}
	if searchDepth == 0 {
		maxConnections := 25 // default
		if input.MaxConnections != nil && *input.MaxConnections > 0 {
			maxConnections = int(*input.MaxConnections)
		}
		r.setSearchStatus(movie.ID.String(), searchStateRunning, nil)
		go func() {
			r.recursiveSearchMovies(context.Background(), movie, maxConnections)
			completedAt := time.Now()
			r.setSearchStatus(movie.ID.String(), searchStateCompleted, &completedAt)
		}()
	}

	return movie, nil
}

// CreateTVShow is the resolver for the createTVShow field.
func (r *mutationResolver) CreateTVShow(ctx context.Context, input model.CreateTVShowInput) (*model.TVShow, error) {
	tvShow, err := r.Repo.CreateTVShow(ctx, input)
	if err != nil {
		return nil, err
	}

	// If searchDepth is 0 (directly searched), perform recursive search on connections
	searchDepth := int32(0)
	if input.SearchDepth != nil {
		searchDepth = *input.SearchDepth
	}
	if searchDepth == 0 {
		maxConnections := 25 // default
		if input.MaxConnections != nil && *input.MaxConnections > 0 {
			maxConnections = int(*input.MaxConnections)
		}
		r.setSearchStatus(tvShow.ID.String(), searchStateRunning, nil)
		go func() {
			r.recursiveSearchTVShows(context.Background(), tvShow, maxConnections)
			completedAt := time.Now()
			r.setSearchStatus(tvShow.ID.String(), searchStateCompleted, &completedAt)
		}()
	}

	return tvShow, nil
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.CreateBookInput) (*model.Book, error) {
	book, err := r.Repo.CreateBook(ctx, input)
	if err != nil {
		return nil, err
	}

	searchDepth := int32(0)
	if input.SearchDepth != nil {
		searchDepth = *input.SearchDepth
	}
	if searchDepth == 0 {
		maxConnections := 25
		r.setSearchStatus(book.ID.String(), searchStateRunning, nil)
		go func() {
			r.recursiveSearchBooks(context.Background(), book, maxConnections)
			completedAt := time.Now()
			r.setSearchStatus(book.ID.String(), searchStateCompleted, &completedAt)
		}()
	}

	return book, nil
}

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input model.CreateGameInput) (*model.Game, error) {
	game, err := r.Repo.CreateGame(ctx, input)
	if err != nil {
		return nil, err
	}

	searchDepth := int32(0)
	if input.SearchDepth != nil {
		searchDepth = *input.SearchDepth
	}
	if searchDepth == 0 {
		maxConnections := 25
		r.setSearchStatus(game.ID.String(), searchStateRunning, nil)
		go func() {
			r.recursiveSearchGames(context.Background(), game, maxConnections)
			completedAt := time.Now()
			r.setSearchStatus(game.ID.String(), searchStateCompleted, &completedAt)
		}()
	}

	return game, nil
}

// CreateMusicAlbum is the resolver for the createMusicAlbum field.
func (r *mutationResolver) CreateMusicAlbum(ctx context.Context, input model.CreateMusicAlbumInput) (*model.MusicAlbum, error) {
	return r.Repo.CreateMusicAlbum(ctx, input)
}

// RateMedia is the resolver for the rateMedia field.
func (r *mutationResolver) RateMedia(ctx context.Context, mediaID uuid.UUID, score float64) (*model.Rating, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.Repo.CreateRating(ctx, currentUser.ID, mediaID, score)
}

// AddToFavorites is the resolver for the addToFavorites field.
func (r *mutationResolver) AddToFavorites(ctx context.Context, mediaID uuid.UUID) (bool, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return false, err
	}
	if err := r.Repo.AddToFavorites(ctx, currentUser.ID, mediaID); err != nil {
		return false, err
	}
	return true, nil
}

// CreateActivity is the resolver for the createActivity field.
func (r *mutationResolver) CreateActivity(ctx context.Context, input model.CreateActivityInput) (*model.UserActivity, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	activity, err := r.Repo.CreateActivity(ctx, currentUser.ID, input)
	if err != nil {
		return nil, err
	}
	// Async: rebuild recommendations for the current user and all their friends.
	go func() {
		_ = r.Repo.BuildRecommendations(context.Background(), currentUser.ID)
		friends, ferr := r.Repo.GetFriends(context.Background(), currentUser.ID)
		if ferr != nil {
			return
		}
		for _, friend := range friends {
			_ = r.Repo.BuildRecommendations(context.Background(), friend.ID)
		}
	}()
	return activity, nil
}

// UpdateActivity is the resolver for the updateActivity field.
func (r *mutationResolver) UpdateActivity(ctx context.Context, id uuid.UUID, input model.UpdateActivityInput) (*model.UserActivity, error) {
	// Get authenticated user
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Validate rating (if provided)
	if input.Rating != nil {
		rating := *input.Rating
		// Check if rating is in valid range
		if rating < 0 || rating > 5 {
			return nil, fmt.Errorf("rating must be between 0 and 5")
		}
		// Check 0.5 increments (multiply by 10 and check mod 5)
		ratingTimes10 := int(rating * 10)
		if ratingTimes10%5 != 0 {
			return nil, fmt.Errorf("rating must be in 0.5 increments")
		}
	}

	// Validate review length (if provided)
	if input.Review != nil {
		review := strings.TrimSpace(*input.Review)
		if len(review) > 140 {
			return nil, fmt.Errorf("review must be 140 characters or less")
		}
		// Update input with trimmed review
		input.Review = &review
	}

	// Auto-set status to Completed if review is being added
	if input.Review != nil && *input.Review != "" && input.StatusID == nil {
		completedStatusID := int32(3)
		input.StatusID = &completedStatusID
	}

	// Call repository method
	return r.Repo.UpdateActivity(ctx, currentUser.ID, id, input)
}

// SendFriendRequest is the resolver for the sendFriendRequest field.
func (r *mutationResolver) SendFriendRequest(ctx context.Context, toUserID uuid.UUID) (*model.FriendRequest, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.Repo.SendFriendRequest(ctx, currentUser.ID, toUserID)
}

// AcceptFriendRequest is the resolver for the acceptFriendRequest field.
func (r *mutationResolver) AcceptFriendRequest(ctx context.Context, requestID uuid.UUID) (*model.User, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	newFriend, err := r.Repo.AcceptFriendRequest(ctx, requestID, currentUser.ID)
	if err != nil {
		return nil, err
	}
	// Async: rebuild recommendations for both users now that they are friends.
	go func() {
		_ = r.Repo.BuildRecommendations(context.Background(), currentUser.ID)
		_ = r.Repo.BuildRecommendations(context.Background(), newFriend.ID)
	}()
	return newFriend, nil
}

// DeclineFriendRequest is the resolver for the declineFriendRequest field.
func (r *mutationResolver) DeclineFriendRequest(ctx context.Context, requestID uuid.UUID) (bool, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return false, err
	}
	return r.Repo.DeclineFriendRequest(ctx, requestID, currentUser.ID)
}

// RemoveFriend is the resolver for the removeFriend field.
func (r *mutationResolver) RemoveFriend(ctx context.Context, friendID uuid.UUID) (bool, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return false, err
	}
	return r.Repo.RemoveFriend(ctx, currentUser.ID, friendID)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*model.User, error) {
	return r.Repo.GetUserByID(ctx, id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.Repo.GetAllUsers(ctx)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, nil
	}
	return r.Repo.GetUserByID(ctx, currentUser.ID)
}

// Media is the resolver for the media field.
func (r *queryResolver) Media(ctx context.Context, id uuid.UUID) (model.Media, error) {
	return r.Repo.GetMediaByID(ctx, id)
}

// AllMedia is the resolver for the allMedia field.
func (r *queryResolver) AllMedia(ctx context.Context) ([]model.Media, error) {
	return r.Repo.GetAllMedia(ctx)
}

// Movies is the resolver for the movies field.
func (r *queryResolver) Movies(ctx context.Context, limit *int32, offset *int32) ([]*model.Movie, error) {
	var l, o *int
	if limit != nil {
		val := int(*limit)
		l = &val
	}
	if offset != nil {
		val := int(*offset)
		o = &val
	}
	return r.Repo.GetAllMovies(ctx, l, o)
}

// TvShows is the resolver for the tvShows field.
func (r *queryResolver) TvShows(ctx context.Context, limit *int32, offset *int32) ([]*model.TVShow, error) {
	var l, o *int
	if limit != nil {
		val := int(*limit)
		l = &val
	}
	if offset != nil {
		val := int(*offset)
		o = &val
	}
	return r.Repo.GetAllTVShows(ctx, l, o)
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context, limit *int32, offset *int32) ([]*model.Book, error) {
	var l, o *int
	if limit != nil {
		val := int(*limit)
		l = &val
	}
	if offset != nil {
		val := int(*offset)
		o = &val
	}
	return r.Repo.GetAllBooks(ctx, l, o)
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context, limit *int32, offset *int32) ([]*model.Game, error) {
	var l, o *int
	if limit != nil {
		val := int(*limit)
		l = &val
	}
	if offset != nil {
		val := int(*offset)
		o = &val
	}
	return r.Repo.GetAllGames(ctx, l, o)
}

// MusicAlbums is the resolver for the musicAlbums field.
func (r *queryResolver) MusicAlbums(ctx context.Context, limit *int32, offset *int32) ([]*model.MusicAlbum, error) {
	var l, o *int
	if limit != nil {
		val := int(*limit)
		l = &val
	}
	if offset != nil {
		val := int(*offset)
		o = &val
	}
	return r.Repo.GetAllMusicAlbums(ctx, l, o)
}

// AutocompleteMedia is the resolver for the autocompleteMedia field.
func (r *queryResolver) AutocompleteMedia(ctx context.Context, typeArg model.MediaType, query string) ([]*model.MediaSuggestion, error) {
	query = strings.TrimSpace(query)
	if query == "" {
		return []*model.MediaSuggestion{}, nil
	}

	metaSvc := r.Repo.GetMetadata()
	if metaSvc == nil {
		return []*model.MediaSuggestion{}, nil
	}

	metadataSvc, ok := metaSvc.(*metadata.Service)
	if !ok {
		return []*model.MediaSuggestion{}, nil
	}

	fetchers := metadataSvc.GetFetchers()
	if fetchers == nil {
		return []*model.MediaSuggestion{}, nil
	}

	switch typeArg {
	case model.MediaTypeMovie, model.MediaTypeTv:
		fetcher, ok := fetchers[metadata.MediaTypeMovie].(*metadata.VideoFetcher)
		if !ok {
			return []*model.MediaSuggestion{}, nil
		}
		isTV := typeArg == model.MediaTypeTv
		results, err := fetcher.SearchTitles(query, isTV, 10)
		if err != nil {
			return nil, err
		}
		return mapVideoSuggestions(results), nil
	case model.MediaTypeBook:
		fetcher, ok := fetchers[metadata.MediaTypeBook].(*metadata.BookFetcher)
		if !ok {
			return []*model.MediaSuggestion{}, nil
		}
		results, err := fetcher.SearchBooksByTitle(query, 10)
		if err != nil {
			return nil, err
		}
		return mapBookSuggestions(results), nil
	case model.MediaTypeGame:
		fetcher, ok := fetchers[metadata.MediaTypeGame].(*metadata.GameFetcher)
		if !ok {
			return []*model.MediaSuggestion{}, nil
		}
		results, err := fetcher.SearchRelatedGames(query)
		if err != nil {
			return nil, err
		}
		return mapGameSuggestions(results, 10), nil
	case model.MediaTypeMusic:
		return []*model.MediaSuggestion{}, nil
	default:
		return []*model.MediaSuggestion{}, nil
	}
}

// RecursiveSearchStatus is the resolver for the recursiveSearchStatus field.
func (r *queryResolver) RecursiveSearchStatus(ctx context.Context, mediaID uuid.UUID) (*model.SearchStatus, error) {
	status := r.getSearchStatus(mediaID.String())
	state := model.SearchStateIdle
	switch status.state {
	case searchStateRunning:
		state = model.SearchStateRunning
	case searchStateCompleted:
		state = model.SearchStateCompleted
	}
	var completedAt *string
	if status.completedAt != nil {
		formatted := status.completedAt.UTC().Format(time.RFC3339)
		completedAt = &formatted
	}
	return &model.SearchStatus{State: state, CompletedAt: completedAt}, nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, query string) ([]*model.User, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	query = strings.TrimSpace(query)
	if query == "" {
		return []*model.User{}, nil
	}
	return r.Repo.SearchUsers(ctx, query, currentUser.ID)
}

// FriendsActivity is the resolver for the friendsActivity field.
func (r *queryResolver) FriendsActivity(ctx context.Context, limit *int32) ([]*model.UserActivity, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = int(*limit)
	}
	return r.Repo.GetFriendsActivity(ctx, currentUser.ID, lim)
}

// GetRecommendations is the resolver for the getRecommendations field.
func (r *queryResolver) GetRecommendations(ctx context.Context) ([]*model.Recommendation, error) {
	currentUser, err := CurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.Repo.GetRecommendations(ctx, currentUser.ID)
}

// CastAndCrew resolves castAndCrew(mediaID: UUID!)
func (r *queryResolver) CastAndCrew(ctx context.Context, mediaID uuid.UUID) (*model.CastAndCrewResult, error) {
	cast, crew, castCredits, crewCredits, err := r.Repo.GetCastAndCrew(ctx, mediaID)
	if err != nil {
		return nil, err
	}
	return &model.CastAndCrewResult{Cast: cast, Crew: crew, CastCredits: castCredits, CrewCredits: crewCredits}, nil
}

// MyActivity is the resolver for the myActivity field.
func (r *tVShowResolver) MyActivity(ctx context.Context, obj *model.TVShow) (*model.UserActivity, error) {
	return r.getMyActivityForMedia(ctx, obj.ID)
}

// RelatedMedia is the resolver for the relatedMedia field.
func (r *tVShowResolver) RelatedMedia(ctx context.Context, obj *model.TVShow, limit *int32) ([]model.Media, error) {
	return r.Repo.GetRelatedMedia(ctx, obj.ID, resolveLimit(limit))
}

// Friends is the resolver for the friends field.
func (r *userResolver) Friends(ctx context.Context, obj *model.User) ([]*model.User, error) {
	return r.Repo.GetFriends(ctx, obj.ID)
}

// PendingFriendRequests is the resolver for the pendingFriendRequests field.
func (r *userResolver) PendingFriendRequests(ctx context.Context, obj *model.User) ([]*model.FriendRequest, error) {
	return r.Repo.GetPendingFriendRequests(ctx, obj.ID)
}

// SentFriendRequests is the resolver for the sentFriendRequests field.
func (r *userResolver) SentFriendRequests(ctx context.Context, obj *model.User) ([]*model.FriendRequest, error) {
	return r.Repo.GetSentFriendRequests(ctx, obj.ID)
}

// Book returns BookResolver implementation.
func (r *Resolver) Book() BookResolver { return &bookResolver{r} }

// FriendRequest returns FriendRequestResolver implementation.
func (r *Resolver) FriendRequest() FriendRequestResolver { return &friendRequestResolver{r} }

// Game returns GameResolver implementation.
func (r *Resolver) Game() GameResolver { return &gameResolver{r} }

// Movie returns MovieResolver implementation.
func (r *Resolver) Movie() MovieResolver { return &movieResolver{r} }

// MusicAlbum returns MusicAlbumResolver implementation.
func (r *Resolver) MusicAlbum() MusicAlbumResolver { return &musicAlbumResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// TVShow returns TVShowResolver implementation.
func (r *Resolver) TVShow() TVShowResolver { return &tVShowResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type bookResolver struct{ *Resolver }
type friendRequestResolver struct{ *Resolver }
type gameResolver struct{ *Resolver }
type movieResolver struct{ *Resolver }
type musicAlbumResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type tVShowResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
