package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"log"
	"strconv"

	"github.com/google/uuid"
	"github.com/grillinr/nq/graph/model"
	"github.com/grillinr/nq/metadata"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	return r.Repo.CreateUser(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, input model.UpdateUserInput) (*model.User, error) {
	return r.Repo.UpdateUser(ctx, id, input)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (bool, error) {
	if err := r.Repo.DeleteUser(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateMovie is the resolver for the createMovie field.
func (r *mutationResolver) CreateMovie(ctx context.Context, input model.CreateMovieInput) (*model.Movie, error) {
	movie, err := r.Repo.CreateMovie(ctx, input)
	if err != nil {
		return nil, err
	}

	// If searchDepth is 0 (directly searched), perform recursive search on connections
	searchDepth := int32(0)
	if input.SearchDepth != nil {
		searchDepth = *input.SearchDepth
	}
	if searchDepth == 0 {
		maxConnections := 5 // default
		if input.MaxConnections != nil && *input.MaxConnections > 0 {
			maxConnections = int(*input.MaxConnections)
		}
		r.recursiveSearchMovies(ctx, movie, maxConnections)
	}

	return movie, nil
}

// CreateTVShow is the resolver for the createTVShow field.
func (r *mutationResolver) CreateTVShow(ctx context.Context, input model.CreateTVShowInput) (*model.TVShow, error) {
	tvShow, err := r.Repo.CreateTVShow(ctx, input)
	if err != nil {
		return nil, err
	}

	// If searchDepth is 0 (directly searched), perform recursive search on connections
	searchDepth := int32(0)
	if input.SearchDepth != nil {
		searchDepth = *input.SearchDepth
	}
	if searchDepth == 0 {
		maxConnections := 5 // default
		if input.MaxConnections != nil && *input.MaxConnections > 0 {
			maxConnections = int(*input.MaxConnections)
		}
		r.recursiveSearchTVShows(ctx, tvShow, maxConnections)
	}

	return tvShow, nil
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.CreateBookInput) (*model.Book, error) {
	return r.Repo.CreateBook(ctx, input)
}

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input model.CreateGameInput) (*model.Game, error) {
	return r.Repo.CreateGame(ctx, input)
}

// CreateMusicAlbum is the resolver for the createMusicAlbum field.
func (r *mutationResolver) CreateMusicAlbum(ctx context.Context, input model.CreateMusicAlbumInput) (*model.MusicAlbum, error) {
	return r.Repo.CreateMusicAlbum(ctx, input)
}

// RateMedia is the resolver for the rateMedia field.
func (r *mutationResolver) RateMedia(ctx context.Context, userID uuid.UUID, mediaID uuid.UUID, score float64) (*model.Rating, error) {
	return r.Repo.CreateRating(ctx, userID, mediaID, score)
}

// AddToFavorites is the resolver for the addToFavorites field.
func (r *mutationResolver) AddToFavorites(ctx context.Context, userID uuid.UUID, mediaID uuid.UUID) (bool, error) {
	if err := r.Repo.AddToFavorites(ctx, userID, mediaID); err != nil {
		return false, err
	}
	return true, nil
}

// CreateActivity is the resolver for the createActivity field.
func (r *mutationResolver) CreateActivity(ctx context.Context, input model.CreateActivityInput) (*model.UserActivity, error) {
	return r.Repo.CreateActivity(ctx, input)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*model.User, error) {
	return r.Repo.GetUserByID(ctx, id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.Repo.GetAllUsers(ctx)
}

// Media is the resolver for the media field.
func (r *queryResolver) Media(ctx context.Context, id uuid.UUID) (model.Media, error) {
	return r.Repo.GetMediaByID(ctx, id)
}

// AllMedia is the resolver for the allMedia field.
func (r *queryResolver) AllMedia(ctx context.Context) ([]model.Media, error) {
	return r.Repo.GetAllMedia(ctx)
}

// Movies is the resolver for the movies field.
func (r *queryResolver) Movies(ctx context.Context) ([]*model.Movie, error) {
	return r.Repo.GetAllMovies(ctx)
}

// TvShows is the resolver for the tvShows field.
func (r *queryResolver) TvShows(ctx context.Context) ([]*model.TVShow, error) {
	return r.Repo.GetAllTVShows(ctx)
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	return r.Repo.GetAllBooks(ctx)
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context) ([]*model.Game, error) {
	return r.Repo.GetAllGames(ctx)
}

// MusicAlbums is the resolver for the musicAlbums field.
func (r *queryResolver) MusicAlbums(ctx context.Context) ([]*model.MusicAlbum, error) {
	return r.Repo.GetAllMusicAlbums(ctx)
}

// CastAndCrew resolves castAndCrew(mediaID: UUID!)
func (r *queryResolver) CastAndCrew(ctx context.Context, mediaID uuid.UUID) (*model.CastAndCrewResult, error) {
	cast, crew, castCredits, crewCredits, err := r.Repo.GetCastAndCrew(ctx, mediaID)
	if err != nil {
		return nil, err
	}
	return &model.CastAndCrewResult{Cast: cast, Crew: crew, CastCredits: castCredits, CrewCredits: crewCredits}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// Helper methods for recursive media search
func (r *mutationResolver) recursiveSearchMovies(ctx context.Context, movie *model.Movie, maxConnections int) {
	log.Printf("Starting recursive search for movie: %s (ID: %s)", movie.Title, movie.ID)
	// Get cast and crew
	for _, person := range movie.Cast {
		if person.ExternalID != nil {
			log.Printf("Searching movies for cast member: %s (ID: %s)", person.Name, *person.ExternalID)
			r.searchPersonMovies(ctx, *person.ExternalID, 1, maxConnections)
		}
	}
	for _, person := range movie.Crew {
		if person.ExternalID != nil {
			log.Printf("Searching movies for crew member: %s (ID: %s)", person.Name, *person.ExternalID)
			r.searchPersonMovies(ctx, *person.ExternalID, 1, maxConnections)
		}
	}
	log.Printf("Completed recursive search for movie: %s", movie.Title)
}
func (r *mutationResolver) recursiveSearchTVShows(ctx context.Context, tvShow *model.TVShow, maxConnections int) {
	log.Printf("Starting recursive search for TV show: %s (ID: %s)", tvShow.Title, tvShow.ID)
	// Get cast and crew
	for _, person := range tvShow.Cast {
		if person.ExternalID != nil {
			log.Printf("Searching TV shows for cast member: %s (ID: %s)", person.Name, *person.ExternalID)
			r.searchPersonTVShows(ctx, *person.ExternalID, 1, maxConnections)
		}
	}
	for _, person := range tvShow.Crew {
		if person.ExternalID != nil {
			log.Printf("Searching TV shows for crew member: %s (ID: %s)", person.Name, *person.ExternalID)
			r.searchPersonTVShows(ctx, *person.ExternalID, 1, maxConnections)
		}
	}
	log.Printf("Completed recursive search for TV show: %s", tvShow.Title)
}
func (r *mutationResolver) searchPersonMovies(ctx context.Context, personID string, searchDepth int32, maxConnections int) {
	log.Printf("Fetching movie credits for person ID: %s", personID)
	metaSvc := r.Repo.GetMetadata()
	if metaSvc == nil {
		log.Printf("Metadata service not available")
		return
	}

	metadataSvc, ok := metaSvc.(*metadata.Service)
	if !ok {
		log.Printf("Failed to cast metadata service")
		return
	}

	fetchers := metadataSvc.GetFetchers()
	if fetchers == nil {
		log.Printf("No fetchers available")
		return
	}

	id, err := strconv.Atoi(personID)
	if err != nil {
		log.Printf("Invalid person ID: %s, error: %v", personID, err)
		return
	}

	videoFetcher, ok := fetchers[metadata.MediaTypeMovie].(*metadata.VideoFetcher)
	if !ok {
		log.Printf("Video fetcher not available")
		return
	}

	movies, err := videoFetcher.FetchPersonMovieCredits(id)
	if err != nil {
		log.Printf("Failed to fetch movie credits for person %s: %v", personID, err)
		return
	}

	log.Printf("Fetched %d movie credits for person %s", len(movies), personID)

	// Limit the number of connections
	if len(movies) > maxConnections {
		log.Printf("Limiting to %d connections (had %d)", maxConnections, len(movies))
		movies = movies[:maxConnections]
	}

	for _, m := range movies {
		log.Printf("Processing movie: %s (%d)", m.Title, m.ReleaseYear)
		// Check if already exists
		existing, err := r.Repo.FindMediaByTitleTypeYear(ctx, m.Title, string(m.Type), &m.ReleaseYear)
		if err == nil && existing != nil {
			log.Printf("Movie %s already exists with depth %d", m.Title, existing.GetSearchDepth())
			// If existing has higher depth, update to lower
			if existing.GetSearchDepth() > searchDepth {
				err = r.Repo.UpdateMediaSearchDepth(ctx, existing.GetID(), searchDepth)
				if err != nil {
					log.Printf("Failed to update search depth for %s: %v", m.Title, err)
				} else {
					log.Printf("Updated search depth for %s to %d", m.Title, searchDepth)
				}
			}
			continue // Already exists
		}

		// Create the movie
		yearStr := strconv.Itoa(m.ReleaseYear)
		input := model.CreateMovieInput{
			Title:       m.Title,
			ReleaseDate: &yearStr,
			Description: &m.Description,
			CoverURL:    &m.ImageURL,
			SearchDepth: &searchDepth,
		}
		_, err = r.Repo.CreateMovie(ctx, input)
		if err != nil {
			log.Printf("Failed to create movie %s: %v", m.Title, err)
		} else {
			log.Printf("Created movie: %s", m.Title)
		}
	}
	log.Printf("Completed processing movies for person %s", personID)
}
func (r *mutationResolver) searchPersonTVShows(ctx context.Context, personID string, searchDepth int32, maxConnections int) {
	log.Printf("Fetching TV show credits for person ID: %s", personID)
	metaSvc := r.Repo.GetMetadata()
	if metaSvc == nil {
		log.Printf("Metadata service not available")
		return
	}

	metadataSvc, ok := metaSvc.(*metadata.Service)
	if !ok {
		log.Printf("Failed to cast metadata service")
		return
	}

	fetchers := metadataSvc.GetFetchers()
	if fetchers == nil {
		log.Printf("No fetchers available")
		return
	}

	id, err := strconv.Atoi(personID)
	if err != nil {
		log.Printf("Invalid person ID: %s, error: %v", personID, err)
		return
	}

	videoFetcher, ok := fetchers[metadata.MediaTypeMovie].(*metadata.VideoFetcher)
	if !ok {
		log.Printf("Video fetcher not available")
		return
	}

	tvShows, err := videoFetcher.FetchPersonTVShowCredits(id)
	if err != nil {
		log.Printf("Failed to fetch TV show credits for person %s: %v", personID, err)
		return
	}

	log.Printf("Fetched %d TV show credits for person %s", len(tvShows), personID)

	// Limit the number of connections
	if len(tvShows) > maxConnections {
		log.Printf("Limiting to %d connections (had %d)", maxConnections, len(tvShows))
		tvShows = tvShows[:maxConnections]
	}

	for _, m := range tvShows {
		log.Printf("Processing TV show: %s (%d)", m.Title, m.ReleaseYear)
		// Check if already exists
		existing, err := r.Repo.FindMediaByTitleTypeYear(ctx, m.Title, string(m.Type), &m.ReleaseYear)
		if err == nil && existing != nil {
			log.Printf("TV show %s already exists with depth %d", m.Title, existing.GetSearchDepth())
			// If existing has higher depth, update to lower
			if existing.GetSearchDepth() > searchDepth {
				err = r.Repo.UpdateMediaSearchDepth(ctx, existing.GetID(), searchDepth)
				if err != nil {
					log.Printf("Failed to update search depth for %s: %v", m.Title, err)
				} else {
					log.Printf("Updated search depth for %s to %d", m.Title, searchDepth)
				}
			}
			continue // Already exists
		}

		// Create the TV show
		yearStr := strconv.Itoa(m.ReleaseYear)
		input := model.CreateTVShowInput{
			Title:       m.Title,
			ReleaseDate: &yearStr,
			Description: &m.Description,
			CoverURL:    &m.ImageURL,
			SearchDepth: &searchDepth,
		}
		_, err = r.Repo.CreateTVShow(ctx, input)
		if err != nil {
			log.Printf("Failed to create TV show %s: %v", m.Title, err)
		} else {
			log.Printf("Created TV show: %s", m.Title)
		}
	}
	log.Printf("Completed processing TV shows for person %s", personID)
}
